=== openTCS/opentcs-commadapter-vda5050/src/main/resources/org/opentcs/commadapter/vehicle/vda5050/v1_1/schemas/instantActions.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "instantActions",
    "documentVersion": "5.0.0",
    "subtopic": "/instantActions",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "headerId": {
            "title": "headerId",
            "type": "integer"
        },
        "timestamp": {
            "title": "timestamp",
            "type": "string",
            "examples": [
                "1991-03-11T11:40:03.12Z"
            ]
        },
        "version": {
            "title": "Version",
            "type": "string",
            "examples": [
                "1.3.2"
            ]
        },
        "manufacturer": {
            "type": "string"
        },
        "serialNumber": {
            "type": "string"
        },
        "instantActions": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "$id": "#instantAction",
                "title": "instantAction",
                "required": [
                    "actionType",
                    "actionId",
                    "blockingType"
                ],
                "properties": {
                    "actionType": {
                        "type": "string",
                        "title": "actionType"
                    },
                    "actionId": {
                        "type": "string",
                        "title": "actionId"
                    },
                    "actionDescription": {
                        "type": [
                          "string",
                          "null"
                        ],
                        "title": "Additional Information on the action"
                    },
                    "blockingType": {
                        "type": "string",
                        "title": "blockingType",
                        "enum": [
                            "NONE",
                            "SOFT",
                            "HARD"
                        ]
                    },
                    "actionParameters": {
                        "type": [
                          "array",
                          "null"
                        ],
                        "items": {
                            "title": "actionParameter",
                            "type": "object",
                            "additionalProperties": false,
                            "required": [
                                "key",
                                "value"
                            ],
                            "properties": {
                                "key": {
                                    "type": "string",
                                    "examples": [
                                        "duration",
                                        "direction",
                                        "signal"
                                    ]
                                },
                                "value": {
                                    "type": [
                                        "array",
                                        "boolean",
                                        "number",
                                        "string"
                                    ],
                                    "examples": [
                                        103.2,
                                        "left",
                                        true,
                                        [
                                            "arrays",
                                            "are",
                                            "also",
                                            "valid"
                                        ]
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "required": [
        "headerId",
        "timestamp",
        "version",
        "manufacturer",
        "serialNumber",
        "instantActions"
    ]
}

=== openTCS/opentcs-commadapter-vda5050/src/test/resources/org/opentcs/commadapter/vehicle/vda5050/v1_1/message/instantactions/instantActionsMessageWithNullForOptionalFields.json
{
  "headerId" : 0,
  "timestamp" : "1970-01-01T00:00:00Z",
  "version" : "version",
  "manufacturer" : "manufacturer",
  "serialNumber" : "serial-number",
  "instantActions" : [ {
    "actionType" : "some-action-type",
    "actionId" : "action1",
    "blockingType" : "NONE",
    "actionDescription" : null,
    "actionParameters" : [ {
      "key" : "some-key",
      "value" : "some-value"
    }]
  }, {
    "actionType" : "some-other-action-type",
    "actionId" : "action2",
    "blockingType" : "SOFT",
    "actionDescription" : null,
    "actionParameters" : null
  } ]
}
